version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpwd
      POSTGRES_DB: db  # Optional: set default database
    ports:
      - "5432:5432"  # Map host port 5432 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
